version: 0.2

phases:
  build:
    commands:
      - cp CommonLibrary/CommonLibrary.csproj .
      - dotnet restore CommonLibrary/CommonLibrary.csproj
      - dotnet build CommonLibrary/CommonLibrary.csproj
      - sudo pwd
  post_build:
    commands:
      - echo "Installing NFS Utilities..."
      - sudo apt-get update
      - sudo apt-get install -y nfs-common
      - echo "Mounting NFS share..."
      - mkdir efs
      - sudo mount -t nfs4 -o nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport fs-1297cf5a.efs.us-east-1.amazonaws.com:/ efs
      - sudo pwd
      - cp bin/Debug/netcoreapp2.0/*.dll efs/
      - echo "Listing contents of the EFS directory:"
      - ls -l efs/
      - echo "Umounting NFS share..."
      - sudo umount efs     
artifacts:
  files:
    - bin/Debug/netcoreapp2.0/*
