version: 0.2

phases:
  install:
    runtime-versions:
        php: 7.3
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --no-include-email --region us-west-1)
      - REPOSITORY_URI=380702768975.dkr.ecr.us-west-1.amazonaws.com/fcdsapidlltest
  
  build:
    commands:
      - ls -la      
      - echo Build started on `date`
      - echo Building the Docker image...        
      - docker build -t testapi .

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker tag testapi $REPOSITORY_URI:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - docker push $REPOSITORY_URI:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - docker tag testapi $REPOSITORY_URI:fcdsrepositorynew
      - docker push $REPOSITORY_URI:fcdsrepositorynew
